//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#add_strategy;
pub(crate) mod r#claim_rewards;
pub(crate) mod r#collect_dust;
pub(crate) mod r#deposit;
pub(crate) mod r#deposit_strategy;
pub(crate) mod r#enable_vault;
pub(crate) mod r#get_unlocked_amount;
pub(crate) mod r#initialize;
pub(crate) mod r#initialize_strategy;
pub(crate) mod r#remove_strategy;
pub(crate) mod r#remove_strategy2;
pub(crate) mod r#set_operator;
pub(crate) mod r#transfer_admin;
pub(crate) mod r#transfer_fee_vault;
pub(crate) mod r#update_locked_profit_degradation;
pub(crate) mod r#withdraw;
pub(crate) mod r#withdraw2;
pub(crate) mod r#withdraw_directly_from_strategy;
pub(crate) mod r#withdraw_strategy;

pub use self::r#add_strategy::*;
pub use self::r#claim_rewards::*;
pub use self::r#collect_dust::*;
pub use self::r#deposit::*;
pub use self::r#deposit_strategy::*;
pub use self::r#enable_vault::*;
pub use self::r#get_unlocked_amount::*;
pub use self::r#initialize::*;
pub use self::r#initialize_strategy::*;
pub use self::r#remove_strategy::*;
pub use self::r#remove_strategy2::*;
pub use self::r#set_operator::*;
pub use self::r#transfer_admin::*;
pub use self::r#transfer_fee_vault::*;
pub use self::r#update_locked_profit_degradation::*;
pub use self::r#withdraw::*;
pub use self::r#withdraw2::*;
pub use self::r#withdraw_directly_from_strategy::*;
pub use self::r#withdraw_strategy::*;
